# docker compose file version 3 to launch python flask application
version: 3

# services to be launched

services:
  # service 1: python flask application
  data-gateway:
    image: data-gateway:8
    # expose port 5000
    ports:
      - "6969:6969"
    # restart the container if it fails
    # restart: always
    environment:
      - PRIVATE_KEY_PATH=/app/config/xternanewkey-private-key
      - SERVER_PORT=3999
      - SENTINEL_CLIENT_ID=cadeaf66-cd7b-4678-ac58-b3d09b56e99d
      - SENTINEL_CLIENT_SECRET=0eQddDgLVmLbWaOo5AybRTVrLViXmB2B
      - STATIONS_CSV_PATH=/app/config/stations.csv
      - IMAGES_PATH=/app/config/images/
      - ENCORD_TEST_DATASET=d5e93353-9aaf-437d-948e-7cdbf37ed80c
      - ENCORD_FORWARD_BRIDGE_DATASET=227ab75e-e12d-4f85-b468-71ea39c145ce
      - ENTSOE_API_KEY=c4700b5b-2451-4389-ab69-ce8d62e7280b
      - ENTSOE_OUTPUT_DIR=/app/data/entsoe-revised-output
      - ENTSOE_ARCHIVE_DIR=/app/data/entsoe-revised-archive
      - ENCORD_LEGACY_BRIDGE_DATASET=85bf029e-7acb-4d4a-b8e2-f09835e4f747
      - ENCORD_LEGACY_BRIDGE_PROJECT=dd63e4d3-4334-48d7-8b7e-493e751f2e40
      - ENCORD_TEST_DATASET=d5e93353-9aaf-437d-948e-7cdbf37ed80c
      - ENCORD_FORWARD_BRIDGE_DATASET=227ab75e-e12d-4f85-b468-71ea39c145ce
      - ENCORD_FORWARD_BRIDGE_PROJECT=a42b4944-7b2b-489b-b606-e8328475effc
      - ENCORD_CATCHUPS_DATASET=b74c498f-7439-49c9-8aba-d84625735c63
      - ALL_BRIDGES_DATAHASHES=/app/data/all_bridges_data_hashes.json
      - ENTSOE_CSV_PATH=/app/data/entsoe-download
    stdin_open: true
    volumes:
      - /home/ubuntu/config:/app/config
      - /home/ubuntu/data:/app/data