UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Andong power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Anegasaki thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Ansan power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Anyang CHP power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Baode Coalbed Methane power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Caoqiao Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Future City Gas and Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Gao''antun Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Jingfeng Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Jingxi Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Shangzhuang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Sun Palace Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Energy Zhuhai Yuhai Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Beijing Zhengdong Electronic Power Group South power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Boryeong power station A';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Bucheon power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Bundang power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Busan power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Chaozhou Shenzhen Energy Fengquan Lake High tech Zone Gas fired Thermal power plant';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Chaozhou Shenzhen Energy Ganlu Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Chentangzhuang power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Chiba thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'China Resources Changzhou Zhonglou Distributed Energy Station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Chita Daini thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Chita thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'CNOOC Funing Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'CNOOC Hainan Yangpu Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'CNOOC Putian Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'CNOOC Shenzhen power plant';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'CNOOC Zhongshan Jiaming Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'CNOOC Zhuhai Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'CR GCL Beijing Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Daegu CHP power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Dangjin Combined Cycle power station A';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Dangjin Combined Cycle power station B';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Datang Baochang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Datang Foshan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Datang Gaoyao Jintao Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Datang Haikou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Jiangshan Xincheng Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Jiangyan Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Jintan Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Lishui Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Shaoxing Jiangbin Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Datang Suzhou Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Datang Wanning Gas power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Dongducheon power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Dongguan Humen Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Dongguan Zhongdian New Energy Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Dongguan Zhongming Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Dongguan Zhongtang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Dongtan 2 CHP power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'East Asia Power Wuxi Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Foshan Funeng Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Funamachi power plant';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Futtsu thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Gaojing power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'GCL Gaozhou Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'GCL Guangzhou Lantian Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'GCL Kunshan Lantian Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'GCL Nanjing Lantian Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'GCL Qinzhou Zhongma Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'GCL Suzhou Economic Zone Lantian Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'GCL Suzhou Economic Zone North Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'GCL Wuxi Lantian Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Guangzhou Pearl River LNG power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guangzhou University City Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Gunsan CC power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guodian Nanxun Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Guodian Zhongshan Minzhong Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guohua Yuyao Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guoxin Gaoyou Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guoxin Huai''an Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guoxin Huai''an No.2 Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Guoxin Yizheng Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Gwangyang power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Hanam CHP power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Hangzhou Banshan power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Hanneng Power Tunkou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Hefei Airport Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Higashi Niigata thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Higashi Ohgishima thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Himeji Daiichi power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Himeji Daini power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huachen Zhangjiagang Huaxing Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Beijing Zhengchangzhuang Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Beiran Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Hangzhou Xiasha Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Jiangdong Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Jiangmen Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Kunshan Thermal power plant';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Longyou Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Nanning Jiangnan Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Pingshan Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Qingyuan Economic Cooperation Zone Gas fired Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Qishuyan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Sanshui Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Shanghai Fengxian Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Shijiazhuang Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Tianjin Beichen Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Tianjin Fuyuan Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huadian Tianjin Nanjiang Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Wangting power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Wuchang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Wujiang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Xiangyang Fancheng Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Yangzhou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Yizheng Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huadian Zengcheng Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huadian Zizhuang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huaneng Beijing power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Chongqing Liangjiang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huaneng Dongguan Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Huaneng Guilin Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Jiangyin Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Nanjing Jinling Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Huaneng Nanshan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Shanghai Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Suzhou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huaneng Taiyuan Dongshan Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Huaneng Tianjin Lingang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Huaneng Yangpu Cogen power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huaneng Zhongyuan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Huanneng Tongxiang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Hwasung power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Ibaraki power plant';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Ichihara power plant';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Ilsan power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Inner Mongolia Sulige Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Ishikariwan Shinko power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'JFE Steel West power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Jiangmen Distributed Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Jiangsu Huafeng Microfiber Distributed Energy Station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Jiangsu Nantong power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Jiangsu Zhenjiang Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Jiangyin Cogen power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Jinjiang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Jiulong Paper Mill power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Joetsu thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'JR East Kawasaki power plant';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Junliangcheng power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Kakowaga Works power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Kashima South Joint power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Kashima thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Kawagoe thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Kawasaki Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Kawasaki thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Kawatetsu Chiba Clean power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'KOMIPO Incheon power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Luoyang Wanzhong Jili Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Minami Yokohama thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Mizushima power plant';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Moka power plant';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Nakasode Clean power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Nanhai Changhai power station A';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Nanjing Liuhe District Yangba power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Nanko power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Niigata thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Niihama Kita thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Ningbo Kefeng Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Ningbo Lvyuan Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Ningxia East Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Nishi Nagoya thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Ohgishima power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Osan CHP power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Oseong power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Paju (KDHC) power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Paju power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Pocheon power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'POSCO Incheon power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Puxing Clean Energy Anji power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Puxing Clean Energy Deneng power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Puxing Clean Energy Lantian power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Puxing Clean Energy Quzhou Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Pyeongtaek power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Pyeongtaek power station B';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Sakai Port power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Sakaide power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Sejong (KOMIPO) power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Senboku Natural Gas power plant';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Sendai thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Seoul power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shanghai Caojing Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shanghai Electric Power Luojing Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shanghai Electric Power Minhang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Shanxi International Electricity Group Taiyuan Jiajie Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shenergy Chongming Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shenergy Shanghai Fengxian Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Shenergy Shanghai Lingang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Shenhua Guohua Beijing Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shennan Power Dongguan Gaobu Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shennan Power Nanshan Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Energy East power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Energy Fengda Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Energy Hongwan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Energy Zhangyang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Meishi Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Shenzhen Yuhu Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Shin Kokura thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Shin Oita power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Shin Sendai thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Shin Minato power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Shin Nagoya thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Shinagawa thermal power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Shinincheon power station A';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Shinincheon power station B';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Sichuan Investment Group Dazhou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Sodegaura thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Soma Port Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Southern Grid Hainan Qinglan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas4' WHERE "name" = 'Southern Grid Hainan Wenchang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'SPIC Changshu Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'SPIC Hengqin Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'SPIC Jiangmen Gaoxin District Distributed Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'SPIC Jiedong Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'SPIC Lisha Island Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'SPIC Sihui Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'SPIC Zhengzhou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'SPIC Zhoukou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'State Grid Lasa Gas power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'T Point 2 power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Tamashima power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Tobata power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Tokyo Gas Bay power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Tokyo Gas Yokosuka power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Toyama Shinko power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Ulsan power station A';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Ulsan power station B';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Wirye CHP power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Wuhan Donghu Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Wuxi West Zone Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Xiamen Dongbu Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Xiaoshan power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Xinjiang Kelamayi power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas1' WHERE "name" = 'Xiyang Coalbed Methane power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Yanai power station';
UPDATE "Station" SET "weatherRegion" = 'KR1' WHERE "name" = 'Yangju CHP power station';
UPDATE "Station" SET "weatherRegion" = 'KR2' WHERE "name" = 'Yeoju Complex power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Yeongnam power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Yeongwol power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Yixing Xielian power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Yokkaichi thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas1' WHERE "name" = 'Yokohama thermal power station';
UPDATE "Station" SET "weatherRegion" = 'JPGas2' WHERE "name" = 'Yoshinoura thermal power plant';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yudean Huadu Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yudean Huizhou Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yudean Shenzhen Qianwan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yudean Xinhui Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yudean Zhongshan Sanjiao Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Yuehua Huangpu power station';
UPDATE "Station" SET "weatherRegion" = 'KR3' WHERE "name" = 'Yulchon power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Changshan Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Changxing Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Jinhua Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Ningbo Zhenhai Power Center Natural Gas Thermal power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Wenzhou Longwan power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Zhenhai Natural Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas2' WHERE "name" = 'Zheneng Zhenhai United power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Zhongshan Nanlang Gas power station';
UPDATE "Station" SET "weatherRegion" = 'CNGas3' WHERE "name" = 'Zhongshan Yong''an Gas Thermal power station';
